version: "3.8"

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
